### ISSUE TITLE
Queries keyword

### ISSUE THREAD

**Issue by hn1e13** [PalindromeLabs/Java-Deserialization-CVEs#1]
Hi, I found that the search results I obtained from cve.mitre.org using the keywords 'Java deserialization' were incomplete. Could you suggest better keywords to use for a more comprehensive search?

**Comment by engn33r** [comment]
I am sorry to say there is no easy automated method. I used the NIST NVD database because the search was slightly better than MITRE. For example, searching for "java deserialization" shows 2 CVEs from 2023 in the MITRE database but 4 CVEs from 2023 in the NVD database. You can search by CWE, CWE-502 was most common. One tactic I used was searching for CVEs for common Java projects, especially projects that had deserialization vulnerabilities in the past (Apache Commons, jackson-databind, etc.). I used many different search queries to generate this list so if you experiment with approaches like this you can manually create a more comprehensive list.

**Comment by hn1e13** [comment]
Thanks for your reply! We found the info we need with your inspiration!
